# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://data4democracy.github.io/educational-hub
title: Data4Democracy Education Resources
email:
description: "Resources for educators, students, and individuals"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/data4democracy
  - title: github
    url: https://github.com/Data4Democracy/educational-hub/
